version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: backend
    command:  sh /app/start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    build: frontend
    ports:
      - "3001:3000"
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: