version: "3.9"  # optional since v1.27.0
services:
  backend:
    image: ghcr.io/jpalczewski/semipaste-backend:latest
    build: backend
    command:  sh /app/start.sh
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    environment:
      - EMAIL_URL=smtp://mailhog:1025

  frontend:
    image: ghcr.io/jpalczewski/semipaste-frontend:latest
    build: frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
  db_data:
