version: "3.9"  # optional since v1.27.0
services:
  backend:
    command:  gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    build:
      context: backend
      args:
        - PRODUCTION=YES