version: "3.9"  # optional since v1.27.0
services:
  backend: &backend
    image: ghcr.io/jpalczewski/semipaste-backend:latest
    build: backend
    command:  sh /app/start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/:/app
    environment:
      - EMAIL_URL=smtp://mailhog:1025
      - PYTHONUNBUFFERED=1

  frontend:
    image: ghcr.io/jpalczewski/semipaste-frontend:latest
    build: frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  celeryworker:
    <<: *backend
    command: sh  /app/start_celeryworker.sh
    ports: []

  celerybeat:
    <<: *backend
    command: sh  /app/start_celerybeat.sh
    ports: []

  flower:
    <<: *backend
    command: sh  /app/start_flower.sh
    ports:
      - "5555:5555"

volumes:
  db_data:
  redis_data:
