version: "3.9"  # optional since v1.27.0
services:
  backend: &backend
    image:  jpalczewski/semipaste-backend:prod-latest
    command: sh /app/start.sh
    build:
      context: backend
      args:
        - PRODUCTION=YES
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DJANGO_CONFIGURATION=Prod
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data_prod:/var/lib/postgresql/data/
  proxy:
    image: jpalczewski/semipaste-proxy:latest
    build:
      context: frontend
      dockerfile: ../proxy/Dockerfile
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "media:/usr/share/nginx/html/media"
    ports:
      - "3030:80"
  celeryworker:
    <<: *backend
    command: sh  /app/start_celeryworker.sh
    ports: []

  celerybeat:
    <<: *backend
    command: sh  /app/start_celerybeat.sh
    ports: []

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data_prod:/data
    command: redis-server --save 60 1 --loglevel warning
volumes:
  db_data_prod:
  redis_data_prod:
  media:
