export const userData = [
  {
    id: "01",
    username: "nazwa01",
    email: "adam.malysz@ski.jump",
    joinDate: "01.01.01",
    lstLoggin: "01.01.01",
    isActive: "true",
  },
  {
    id: "02",
    username: "nazwa02",
    email: "adam.malysz@ski.jump",
    joinDate: "02.02.02",
    lstLoggin: "02.02.02",
    isActive: "true",
  },
  {
    id: "03",
    username: "nazwa03",
    email: "adam.malysz@ski.jump",
    joinDate: "03.03.03",
    lstLoggin: "03.03.03",
    isActive: "true",
  },
  {
    id: "04",
    username: "nazwa04",
    email: "adam.malysz@ski.jump",
    joinDate: "04.04.04",
    lstLoggin: "04.04.04",
    isActive: "true",
  },
  {
    id: "05",
    username: "nazwa05",
    email: "adam.malysz@ski.jump",
    joinDate: "05.05.05",
    lstLoggin: "05.05.05",
    isActive: "true",
  },
  {
    id: "06",
    username: "nazwa06",
    email: "adam.malysz@ski.jump",
    joinDate: "06.06.06",
    lstLoggin: "06.06.06",
    isActive: "true",
  },
];
