# Generated by Django 4.0.3 on 2022-04-20 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastes', '0008_alter_attachment_paste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(verbose_name='liked or disliked')),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastes.pastebin', verbose_name='rated paste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='rater')),
            ],
        ),
    ]
