# Generated by Django 4.0.3 on 2022-04-20 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='liked',
            field=models.BooleanField(verbose_name='liked [true] or disliked [false]'),
        ),
    ]
