# Generated by Django 4.0.3 on 2022-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Description', verbose_name='description'),
            preserve_default=False,
        ),
    ]
