# Generated by Django 4.0.3 on 2022-04-06 06:52

from django.db import migrations, models
import django.db.models.deletion
import pastes.models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_alter_pastebin_expire_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pastes.models.Attachment.get_attachment_filename)),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastes.pastebin')),
            ],
        ),
    ]
