# Generated by Django 4.0.3 on 2022-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_alter_pastebin_expire_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='language',
            field=models.CharField(default='Plain Text', max_length=50, verbose_name='langauge'),
        ),
    ]
