# Generated by Django 4.0.3 on 2022-04-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0005_pastebin_attachment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='attachment_token',
            field=models.CharField(db_index=True, max_length=32, verbose_name='token issued to upload attachments'),
        ),
    ]
