# Generated by Django 4.0.3 on 2022-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0008_alter_attachment_paste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.RemoveField(
            model_name='pastebin',
            name='exposure',
        ),
        migrations.AddField(
            model_name='pastebin',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
