# Generated by Django 4.0.4 on 2022-04-23 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastes', '0009_alter_attachment_options_remove_pastebin_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='total_rating',
            field=models.IntegerField(default=0, verbose_name='total number of likes and dislikes'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(null=True, verbose_name='liked [true] or disliked [false]')),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastes.pastebin', verbose_name='rated paste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='rater')),
            ],
        ),
    ]
