# Generated by Django 4.0.4 on 2022-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0010_alter_pastebin_attachment_token_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='dislikes'),
        ),
        migrations.AddField(
            model_name='pastebin',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
    ]
