# Generated by Django 4.0.4 on 2022-04-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0010_pastetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastetag',
            name='paste_id_list',
        ),
        migrations.CreateModel(
            name='MTMTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastes.pastebin')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastes.pastetag')),
            ],
        ),
    ]
