# Generated by Django 4.0.4 on 2022-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0011_pastebin_dislikes_pastebin_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='date_of_creation',
            field=models.DateField(blank=True, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='date of expiry'),
        ),
    ]
