# Generated by Django 4.0.4 on 2022-04-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0011_remove_pastetag_paste_id_list_mtmtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtmtags',
            old_name='paste_id',
            new_name='paste',
        ),
        migrations.RenameField(
            model_name='mtmtags',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
