# Generated by Django 4.0.4 on 2022-05-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0011_pastebin_dislikes_pastebin_likes'),
        ('pastes', '0012_rename_paste_id_mtmtags_paste_and_more'),
    ]

    operations = [
    ]
